# Generated by Django 5.0.3 on 2024-03-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodel',
            old_name='fnm',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='lnm',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='pas',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signupmodel',
            old_name='unm',
            new_name='username',
        ),
    ]
