# Generated by Django 5.0.3 on 2024-03-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l_app', '0002_rename_fnm_signupmodel_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tripModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('place', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
